# Generated by Django 4.2.4 on 2024-03-12 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_career', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='CareerSubjectYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile_api.career')),
            ],
            options={
                'verbose_name': 'Carrera y materia',
                'verbose_name_plural': 'Carrera y materias',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, unique=True)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('date_purchased', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_synchronized', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_id', models.IntegerField(blank=True, verbose_name='ID de horario')),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=255)),
                ('career_subject_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile_api.careersubjectyear')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile_api.device', verbose_name='Dispositivos')),
            ],
            options={
                'verbose_name': 'Horario de materia',
                'verbose_name_plural': 'Horario de materias',
                'unique_together': {('horario_id', 'device')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_device_id', models.IntegerField(blank=True, unique=True, verbose_name='ID de usuario')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=100, null=True, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('gender', models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer'), ('unknown', 'Sin especificar')], max_length=10, verbose_name='Género')),
                ('userVerifyMode', models.CharField(blank=True, choices=[('cardOrFace', 'Tarjeta o cara'), ('cardOrfaceOrPw', 'Tarjeta, cara o clave'), ('cardOrPw', 'Tarjeta o clave'), ('card', 'Tarjeta'), ('cardOrFace', 'Cara o clave'), ('face', 'Cara'), ('cardOrFaceOrFp', 'Cara, tarjeta o huella'), ('fpOrface', 'Cara o huella')], max_length=30, verbose_name='Tipo de verificación')),
                ('doorRight', models.CharField(max_length=100, verbose_name='Puerta proxima')),
                ('doorNo', models.CharField(max_length=100, verbose_name='Número de puerta')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Usuario habilitado?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Usuario administrador?')),
                ('profile_type', models.CharField(choices=[('normal', 'Normal'), ('visitor', 'Visitante'), ('blackList', 'Bloqueado')], max_length=10, verbose_name='Tipo de usuario')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha creación')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha actualización')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('beginTime', models.DateTimeField(verbose_name='Fecha inicio de habilitación')),
                ('endTime', models.DateTimeField(verbose_name='Fecha final de habilitación')),
                ('fileImage', models.FileField(blank=True, upload_to='user_profile_api/images/', verbose_name='Imagen')),
                ('card', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Tarjeta')),
                ('cardType', models.CharField(blank=True, choices=[('normalCard', 'Normal'), ('patrolCard', 'Mantenimiento'), ('hijackCard', 'Hijack'), ('superCard', 'Super'), ('dismissingCard', 'Destituir'), ('emergencyCard', 'Emergencia')], max_length=20, verbose_name='Tipo de tarjeta')),
                ('timeType', models.CharField(default='local', max_length=10, verbose_name='Modo de hora')),
                ('fingerprint', models.TextField(blank=True, null=True)),
                ('subject', models.ManyToManyField(to='user_profile_api.subjectschedule', verbose_name='Materias a asistir')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile_api.device')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AddField(
            model_name='careersubjectyear',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile_api.subject'),
        ),
    ]
