# Generated by Django 4.1.7 on 2023-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=20),
        ),
    ]
