# Generated by Django 4.1.7 on 2023-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0002_alter_subjectschedule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectschedule',
            name='day',
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='Dias', to='user_profile_api.dias'),
        ),
    ]
