# Generated by Django 4.1.7 on 2023-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0003_dias_remove_subjectschedule_day_subjectschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectschedule',
            name='day',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], default='Lunes', max_length=20),
            preserve_default=False,
        ),
    ]
