# Generated by Django 4.1.7 on 2023-04-26 06:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0006_alter_subjectschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedule',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=100),
        ),
    ]
